local _, GGM = ...

GGM.SCHEMA_VERSION = 7

GGM.PROFESSION_MAX_RECIPES = 4096
GGM.PROFESSION_MAX_NAME_BYTES = 128
GGM.PROFESSION_SOURCE_GUILD_LINK = "guild-profession-link"
GGM.PROFESSION_SOURCE_PLAYER = "player"
GGM.PROFESSION_CACHE_STATUS = "cached"
GGM.PROFESSION_RECIPE_INDEX_VERSION = 3
